environment:
  matrix:
    - PYTHON: "C:\\Python27"
      APPVEYOR_PYTHON_VERSION: "2.7.x" # currently 2.7.11

    - PYTHON: "C:\\Python34"
      APPVEYOR_PYTHON_VERSION: "3.4.x" # currently 3.4.3

init:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "ECHO PATH=%PATH%"
  - python --version

build: off

install:
  - pip install tox wheel

# Tox runs v2.2.0 with --jobs 32, which fails on Windows with
# AttributeError: 'FlakesChecker' object has no attribute 'withDoctest'
test_script:
  - tox -e pytest
  - tox -e v250,v240,v230,v224,v210,v200

deploy_script:
  - python setup.py sdist bdist_wheel

artifacts:
  - path: dist\* .coverage coverage.xml
