language: python
sudo: false

python:
- 2.6
- 2.7
- 3.2
- 3.3
- 3.4
- 3.5
- pypy
- pypy3

env:
  global:
    # Workaround for https://github.com/jayvdb/flake8-putty/issues/16
    - VIRTUALENV_DOWNLOAD=no
    - VIRTUALENV_WHEEL=no
  matrix:
    - TOXENV=v26x,v255,v241,v230,v224,v220,v210,v200
    - TOXENV=green
    - TOXENV=pytest

matrix:
  include:
    - env: TOXENV=test
      python: 3.4
  exclude:
    # green does not work on Python 2.6
    - env: TOXENV=green
      python: 2.6
    # Remove some other green and pytest builds as they are almost identical
    - env: TOXENV=pytest
      python: 3.2
    - env: TOXENV=green
      python: 3.3
    - env: TOXENV=pytest
      python: pypy
    - env: TOXENV=green
      python: pypy3

install:
  - pip install -U -r test-requirements.txt

script:
- tox
